package main

//
// a MR application you need to develop
// go build -buildmode=plugin credit.go
//

import (
	"cs350/mr"
	"strconv"
	"strings"
)

// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
func Map(filename string, contents string) []mr.KeyValue {
	var kva []mr.KeyValue
	lines := strings.Split(contents, "\n")
	for i, line := range lines {
		// skip the first line
		if i == 0 {
			continue
		}

		fields := strings.Split(line, ",")
		// Assuming the CSV doesn't have a header or it's already removed
		if len(fields) == 4 {
			year, errYear := strconv.Atoi(fields[2])
			score, errScore := strconv.Atoi(fields[3])
			if errYear == nil && errScore == nil && year == 2023 && score > 400 {
				kva = append(kva, mr.KeyValue{fields[1], "1"})
			}
		}
	}
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func Reduce(key string, values []string) string {
	return strconv.Itoa(len(values))
}
